---
- name: NGINX repo install
  template:
    src: "templates/etc/yum.repos.d/{{ item }}.j2"
    dest: "/etc/yum.repos.d/{{ item }}"
    mode: 0644
    owner: root
    group: root
  loop:
    - nginx.repo

- name: ensure nginx is at the latest version
  yum:
    name: nginx
    state: present
    update_cache: yes
    enablerepo: nginx